name: Build and Deploy GitHub Pages

# Spustí se při každém pushnutí do větve 'main'
on:
  push:
    branches:
      - main
      - website
  # Umožňuje ruční spuštění z panelu Actions
  workflow_dispatch:

# Oprávnění potřebná pro workflow, aby mohlo zapisovat do repozitáře
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies 📦
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate static site ⚙️
        run: python scripts/generate_site.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Složka, kde jsou vygenerované soubory
          publish_dir: ./dist
