name: Update Formulas and Casks

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update formulas and casks
        run: |
          brew bump-formula-pr

          brew bump-cask-pr
